config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :post_images, only: [:new, :create, :index, :show, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image

  belongs_to :user

  # 画像が設定されない場合はapp/assets/images/NoImage.jpgという画像を表示
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/NoImage.jpg')
      image.attach(io: File.open(file_path), filename: 'NoImage.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Deviseが用意しているメソッド。サインイン後にどこに遷移するかを設定
  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  # protectedは呼び出された他のコントローラからも参照することができる
  protected

  # ユーザー登録(sign_up)の際に、ユーザー名(name)のデータ操作を許可する
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/postimages_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
  end

  # 投稿データの保存
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path, notice: "投稿成功ました。"
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.all
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  # 投稿データのストロングパラメータ
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <% if user_signed_in? %>
      <li>
        <%= link_to "All list", post_images_path %>
      </li>
      <li>
        <%= link_to "New post", new_post_image_path %>
      </li>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Sign in", new_user_session_path %>
      </li>
    <% end %>
  </header>    <main>
      <%= yield %>
    </main>
    <footer>

    </footer>
  </body>
</html>

app/views/postimages/index.html.erb
<h1>投稿一覧</h1>

<% @post_images.each do |post_image| %>
  <div>
    <%= image_tag post_image.get_image %>
    <p>投稿ユーザー画像：<%= image_tag 'NoImage.jpg' %></p>
    <p>ショップ名：<%= post_image.shop_name %></p>
    <p>説明：<%= post_image.caption %></p>
    <p>ユーザーネーム：<%= post_image.user.name %></p>
  </div>
<% end %>

app/views/postimages/new.html.erb
<h1>画像投稿フォーム</h1>
<% if @post_image.errors.any? %>
  <%= @post_image.errors.count %>件のエラーが発生しました
  <% @post_image.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model: @post_image do |f| %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>

  <h4>説明</h4>
  <%= f.text_area :caption %>

  <%= f.submit '投稿' %>

<% end %>

app/views/postimages/show.html.erb
<h1>Postimages#show</h1>
<p>Find me in app/views/postimages/show.html.erb</p>